// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// joybus //
// ------ //

#define joybus_wrap_target 10
#define joybus_wrap 21
#define joybus_pio_version 0

#define joybus_T1 10
#define joybus_T2 20
#define joybus_T3 10

#define joybus_offset_read 0u
#define joybus_offset_write 9u

static const uint16_t joybus_program_instructions[] = {
    0xe080, //  0: set    pindirs, 0
    0x3320, //  1: wait   0 pin, 0               [19]
    0x4001, //  2: in     pins, 1
    0x20a0, //  3: wait   1 pin, 0
    0x0001, //  4: jmp    1
    0xa442, //  5: nop                           [4]
    0xe900, //  6: set    pins, 0                [9]
    0xf201, //  7: set    pins, 1                [18]
    0x0000, //  8: jmp    0
    0xe081, //  9: set    pindirs, 1
            //     .wrap_target
    0xe001, // 10: set    pins, 1
    0x80e0, // 11: pull   ifempty block
    0x6021, // 12: out    x, 1
    0x00f2, // 13: jmp    !osre, 18
    0x00a5, // 14: jmp    x != y, 5
    0x80e0, // 15: pull   ifempty block
    0x6021, // 16: out    x, 1
    0x0013, // 17: jmp    19
    0xa342, // 18: nop                           [3]
    0xa142, // 19: nop                           [1]
    0xe900, // 20: set    pins, 0                [9]
    0xb201, // 21: mov    pins, x                [18]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program joybus_program = {
    .instructions = joybus_program_instructions,
    .length = 22,
    .origin = -1,
    .pio_version = joybus_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config joybus_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + joybus_wrap_target, offset + joybus_wrap);
    return c;
}

#include <hardware/clocks.h>
static inline pio_sm_config joybus_program_get_config(PIO pio, uint sm, uint offset, uint pin) {
    pio_gpio_init(pio, pin);
    gpio_pull_up(pin);  // Joybus open-drain requires pull-up for idle-high
    pio_sm_config c = joybus_program_get_default_config(offset);
    sm_config_set_out_pins(&c, pin, 1);
    sm_config_set_set_pins(&c, pin, 1);
    sm_config_set_in_pins(&c, pin);
    // Shift to left, no autopull, 9 bit
    sm_config_set_out_shift(&c, false, false, 9);
    // Shift to left, autopush, 8 bit
    sm_config_set_in_shift(&c, false, true, 8);
    int cycles_per_bit = joybus_T1 + joybus_T2 + joybus_T3;
    int bitrate = 250000;
    float div = clock_get_hz(clk_sys) / (cycles_per_bit * bitrate);
    sm_config_set_clkdiv(&c, div);
    return c;
}
static inline void joybus_program_send_init(
    PIO pio,
    uint sm,
    uint offset,
    uint pin,
    pio_sm_config *c
) {
    pio_sm_init(pio, sm, offset + joybus_offset_write, c);
    pio_sm_set_enabled(pio, sm, true);
}
static inline void joybus_program_receive_init(
    PIO pio,
    uint sm,
    uint offset,
    uint pin,
    pio_sm_config *c
) {
    pio_sm_init(pio, sm, offset + joybus_offset_read, c);
    pio_sm_set_enabled(pio, sm, true);
}

// Fully atomic SM init for multi-core safety
// Unlike pio_sm_init(), this uses hw_clear_bits/hw_set_bits instead of
// non-atomic read-modify-write on pio->ctrl. This prevents race conditions
// when multiple cores share the same PIO instance.
#include <hardware/sync.h>
#include <hardware/pio_instructions.h>

static inline void joybus_sm_init_atomic(PIO pio, uint sm, uint initial_pc, const pio_sm_config *c) {
    // Disable SM atomically (pio_sm_set_enabled uses non-atomic read-modify-write!)
    hw_clear_bits(&pio->ctrl, 1u << sm);

    // Set config (writes to SM-specific registers, safe)
    pio_sm_set_config(pio, sm, c);

    // Clear FIFOs (uses hw_xor_bits on SM-specific register, safe)
    pio_sm_clear_fifos(pio, sm);

    // Clear FIFO debug flags (direct write to SM-indexed bits)
    const uint32_t fdebug_sm_mask =
        (1u << PIO_FDEBUG_TXOVER_LSB) |
        (1u << PIO_FDEBUG_RXUNDER_LSB) |
        (1u << PIO_FDEBUG_TXSTALL_LSB) |
        (1u << PIO_FDEBUG_RXSTALL_LSB);
    pio->fdebug = fdebug_sm_mask << sm;

    // Restart SM (uses hw_set_bits, atomic)
    pio_sm_restart(pio, sm);
    pio_sm_clkdiv_restart(pio, sm);

    // Set initial PC (writes to SM-specific register)
    pio_sm_exec(pio, sm, pio_encode_jmp(initial_pc));
}

static inline void joybus_program_send_init_atomic(
    PIO pio,
    uint sm,
    uint offset,
    uint pin,
    pio_sm_config *c
) {
    joybus_sm_init_atomic(pio, sm, offset + joybus_offset_write, c);
    hw_set_bits(&pio->ctrl, 1u << sm);  // Atomic enable
}
static inline void joybus_program_receive_init_atomic(
    PIO pio,
    uint sm,
    uint offset,
    uint pin,
    pio_sm_config *c
) {
    joybus_sm_init_atomic(pio, sm, offset + joybus_offset_read, c);
    hw_set_bits(&pio->ctrl, 1u << sm);  // Atomic enable
}

#endif
